/**
 * Упаковывает data/warehouse.db в TypeScript-модуль для Cloudflare Workers,
 * где нет доступа к файловой системе проекта.
 */
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const dbPath = path.join(root, "data", "warehouse.db");
const outPath = path.join(root, "src", "lib", "warehouse.embedded.ts");

if (!fs.existsSync(dbPath)) {
  console.error("Нет data/warehouse.db — сначала npm run etl");
  process.exit(1);
}

const b64 = fs.readFileSync(dbPath).toString("base64");
const source =
  `/* eslint-disable */\n` +
  `// AUTO-GENERATED by scripts/embed-warehouse.ts — не редактировать вручную\n` +
  `export const WAREHOUSE_DB_BASE64 = "${b64}";\n`;

fs.writeFileSync(outPath, source);
console.log(
  `Embedded warehouse.db → ${path.relative(root, outPath)} (${Math.round(b64.length / 1024)} KB base64)`,
);
